-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/S6nLiK
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE `ORDER` (
    `ROW_ID` INT  NOT NULL ,
    `ORDER_ID` INT  NOT NULL ,
    `DATE_CREATED` DATE  NOT NULL ,
    `QUANTITY` INT  NOT NULL ,
    `CUS_ID` INT  NOT NULL ,
    `ITEM_ID` INT  NOT NULL ,
    `DELIVERY` BOOLEAN  NOT NULL ,
    `ADD_ID` INT  NOT NULL ,
    PRIMARY KEY (
        `ROW_ID`
    )
);

CREATE TABLE `CUSTOMER` (
    `CUS_ID` INT  NOT NULL ,
    `CUS_FIRST_NAME` VARCHAR(200)  NOT NULL ,
    `CUS_LAST_NAME` VARCHAR(200)  NOT NULL ,
    PRIMARY KEY (
        `CUS_ID`
    )
);

CREATE TABLE `DELIVERY` (
    `ADD_ID` VARCHAR(200)  NOT NULL ,
    `DELIVERY_ADDRESS_1` VARCHAR(200)  NOT NULL ,
    `DELIVERY_ADDRESS_2` VARCHAR(200)  NOT NULL ,
    `DELIVERY_CITY` VARCHAR(25)  NOT NULL ,
    `DELIVERY_ZIP_CODE` INT  NOT NULL 
);

CREATE TABLE `ITEM` (
    `ITEM_ID` INT  NOT NULL ,
    `SKU` VARCHAR(20)  NOT NULL ,
    `ITEM_NAME` VARCHAR(45)  NOT NULL ,
    `ITEM_CATEGORY` VARCHAR(45)  NOT NULL ,
    `ITEM_SIZE` VARCHAR(45)  NOT NULL ,
    `ITEM_PRICE` DECIMAL(5,2)  NOT NULL ,
    PRIMARY KEY (
        `ITEM_ID`
    )
);

CREATE TABLE `INGREDIENT` (
    `ING_ID` INT  NOT NULL ,
    `ING_NAME` VARCHAR(200)  NOT NULL ,
    `ING_WEIGHT` DECIMAL(5,2)  NOT NULL ,
    `ING_PRICE` DECIMAL(5,2)  NOT NULL ,
    `ING_MASS` DECIMAL(5,2)  NOT NULL ,
    PRIMARY KEY (
        `ING_ID`
    )
);

CREATE TABLE `RECIPE` (
    `ROW_ID` INT  NOT NULL ,
    `RECIPE_ID` VARCHAR(200)  NOT NULL ,
    `ING_ID` INT  NOT NULL ,
    `QUANTITY` DECIMAL(4,2)  NOT NULL ,
    PRIMARY KEY (
        `ROW_ID`
    )
);

CREATE TABLE `INVENTORY` (
    `INV_ID` INT  NOT NULL ,
    `ITEM_ID` INT  NOT NULL ,
    `QUANTITY` INT  NOT NULL ,
    PRIMARY KEY (
        `INV_ID`
    )
);

CREATE TABLE `STAFF` (
    `EMP_ID` INT  NOT NULL ,
    `EMP_FIRST_NAME` VARCHAR(200)  NOT NULL ,
    `EMP_LAST_NAME` VARCHAR(200)  NOT NULL ,
    `EMP_POSITION` VARCHAR(40)  NOT NULL ,
    `HOUR_RATE` TIMESTAMP  NOT NULL ,
    PRIMARY KEY (
        `EMP_ID`
    )
);

CREATE TABLE `SHIFTDATE` (
    `SHIFT_ID` INT  NOT NULL ,
    `DAYS_OF_WEEK` VARCHAR(20)  NOT NULL ,
    `TIME` TIMESTAMP  NOT NULL ,
    `END_TIME` TIMESTAMP  NOT NULL ,
    PRIMARY KEY (
        `SHIFT_ID`
    )
);

CREATE TABLE `ROTATE` (
    `ROW_ID` INT  NOT NULL ,
    `ROTATION_ID` VARCHAR(20)  NOT NULL ,
    `SHIFT_ID` VARCHAR(20)  NOT NULL ,
    `DATE` DATE  NOT NULL ,
    `STAFF_ID` VARCHAR(20)  NOT NULL ,
    PRIMARY KEY (
        `ROW_ID`
    )
);

ALTER TABLE `ORDER` ADD CONSTRAINT `fk_ORDER_DATE_CREATED` FOREIGN KEY(`DATE_CREATED`)
REFERENCES `ROTATE` (`DATE`);

ALTER TABLE `CUSTOMER` ADD CONSTRAINT `fk_CUSTOMER_CUS_ID` FOREIGN KEY(`CUS_ID`)
REFERENCES `ORDER` (`CUS_ID`);

ALTER TABLE `DELIVERY` ADD CONSTRAINT `fk_DELIVERY_ADD_ID` FOREIGN KEY(`ADD_ID`)
REFERENCES `ORDER` (`ADD_ID`);

ALTER TABLE `ITEM` ADD CONSTRAINT `fk_ITEM_ITEM_ID` FOREIGN KEY(`ITEM_ID`)
REFERENCES `ORDER` (`ITEM_ID`);

ALTER TABLE `RECIPE` ADD CONSTRAINT `fk_RECIPE_RECIPE_ID` FOREIGN KEY(`RECIPE_ID`)
REFERENCES `ITEM` (`SKU`);

ALTER TABLE `INVENTORY` ADD CONSTRAINT `fk_INVENTORY_ITEM_ID` FOREIGN KEY(`ITEM_ID`)
REFERENCES `ORDER` (`ITEM_ID`);

ALTER TABLE `INVENTORY` ADD CONSTRAINT `fk_INVENTORY_QUANTITY` FOREIGN KEY(`QUANTITY`)
REFERENCES `RECIPE` (`QUANTITY`);

ALTER TABLE `STAFF` ADD CONSTRAINT `fk_STAFF_EMP_ID` FOREIGN KEY(`EMP_ID`)
REFERENCES `ROTATE` (`STAFF_ID`);

ALTER TABLE `SHIFTDATE` ADD CONSTRAINT `fk_SHIFTDATE_SHIFT_ID` FOREIGN KEY(`SHIFT_ID`)
REFERENCES `ROTATE` (`SHIFT_ID`);

